{{- if .Values.homepage.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shape-network-node.fullname" . }}-homepage
  labels:
    {{- include "shape-network-node.labels" . | nindent 4 }}
    component: homepage
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "shape-network-node.selectorLabels" . | nindent 4 }}
    component: homepage
{{- end }}
