apiVersion: v1
kind: Service
metadata:
  name: {{ include "shape-network-node.fullname" . }}-op-geth
  labels:
    {{- include "shape-network-node.labels" . | nindent 4 }}
    component: op-geth
spec:
  type: ClusterIP
  ports:
  - port: 8545
    targetPort: http-rpc
    protocol: TCP
    name: http-rpc
  - port: 8546
    targetPort: ws-rpc
    protocol: TCP
    name: ws-rpc
  - port: 8551
    targetPort: authrpc
    protocol: TCP
    name: authrpc
  - port: 6060
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "shape-network-node.selectorLabels" . | nindent 4 }}
    component: op-geth
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shape-network-node.fullname" . }}-op-node
  labels:
    {{- include "shape-network-node.labels" . | nindent 4 }}
    component: op-node
spec:
  type: ClusterIP
  ports:
  - port: 9545
    targetPort: rpc
    protocol: TCP
    name: rpc
  - port: 7300
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "shape-network-node.selectorLabels" . | nindent 4 }}
    component: op-node
---
{{- if .Values.monitoring.healthcheck.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shape-network-node.fullname" . }}-healthcheck
  labels:
    {{- include "shape-network-node.labels" . | nindent 4 }}
    component: healthcheck
spec:
  type: ClusterIP
  ports:
  - port: 7300
    targetPort: metrics
    protocol: TCP
    name: metrics
  selector:
    {{- include "shape-network-node.selectorLabels" . | nindent 4 }}
    component: healthcheck
---
{{- end }}
{{- if eq .Values.service.type "LoadBalancer" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "shape-network-node.fullname" . }}-external
  labels:
    {{- include "shape-network-node.labels" . | nindent 4 }}
    component: external
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: "{{ .Values.service.azure.resourceGroup }}"
    service.beta.kubernetes.io/azure-pip-name: "{{ .Values.service.azure.staticIpName }}"
spec:
  type: LoadBalancer
  ports:
  - port: {{ .Values.service.ports.httpRpc }}
    targetPort: http-rpc
    protocol: TCP
    name: http-rpc
  - port: {{ .Values.service.ports.wsRpc }}
    targetPort: ws-rpc
    protocol: TCP
    name: ws-rpc
  selector:
    {{- include "shape-network-node.selectorLabels" . | nindent 4 }}
    component: op-geth
{{- end }}
